### ISSUE TITLE
R9 missing from code table

### ISSUE THREAD

**Issue by arttu-karpinlehto** [skoolkid/jetsetwilly#1]
The last protection code R9 (2423) at 0x9EB3 is not included in the Codes table and is instead listed in the Unused addresses.

**Comment by skoolkid** [comment]
Yes, I left it out of the Codes table because it's [never used](https://skoolkid.github.io/jetsetwilly/reference/facts.html#unusedGridLocation).

**Comment by arttu-karpinlehto** [comment]
Got it.  (Sorry, I didn't read the trivia page through.)
